// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClirEjnvxPRhFYv7_4QWhuIoYqUr_uIJE',
    appId: '1:337349884372:web:79458f2939b40bcc4a3e41',
    messagingSenderId: '337349884372',
    projectId: 'mvp2025-d40f9',
    authDomain: 'mvp2025-d40f9.firebaseapp.com',
    storageBucket: 'mvp2025-d40f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkRrdxBod70mUucLHO23ekOBHknFXe2lg',
    appId: '1:337349884372:android:c8e8c8adc6e295694a3e41',
    messagingSenderId: '337349884372',
    projectId: 'mvp2025-d40f9',
    storageBucket: 'mvp2025-d40f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd3ChURi8_nhrfXeVsbuaceqZhI8_4bmo',
    appId: '1:337349884372:ios:a90c27073f9b5f424a3e41',
    messagingSenderId: '337349884372',
    projectId: 'mvp2025-d40f9',
    storageBucket: 'mvp2025-d40f9.firebasestorage.app',
    iosBundleId: 'com.example.mvp',
  );
}
