// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgjOCBaJQtPfChvql95lLK1Bh6zzgF1S8',
    appId: '1:295894338538:web:7b6d5d0865b3d2e7080093',
    messagingSenderId: '295894338538',
    projectId: 'coba-f3b2f',
    authDomain: 'coba-f3b2f.firebaseapp.com',
    storageBucket: 'coba-f3b2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-axp_WL46GpHBlSg7UsPHvR_j7NjTJrY',
    appId: '1:295894338538:android:823234eb0559c78e080093',
    messagingSenderId: '295894338538',
    projectId: 'coba-f3b2f',
    storageBucket: 'coba-f3b2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsJWFaadHeJi6m_-JStZhxeYCE4oC7t9c',
    appId: '1:295894338538:ios:33a91693d54dab35080093',
    messagingSenderId: '295894338538',
    projectId: 'coba-f3b2f',
    storageBucket: 'coba-f3b2f.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsJWFaadHeJi6m_-JStZhxeYCE4oC7t9c',
    appId: '1:295894338538:ios:33a91693d54dab35080093',
    messagingSenderId: '295894338538',
    projectId: 'coba-f3b2f',
    storageBucket: 'coba-f3b2f.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgjOCBaJQtPfChvql95lLK1Bh6zzgF1S8',
    appId: '1:295894338538:web:52b45895d17c7f21080093',
    messagingSenderId: '295894338538',
    projectId: 'coba-f3b2f',
    authDomain: 'coba-f3b2f.firebaseapp.com',
    storageBucket: 'coba-f3b2f.firebasestorage.app',
  );
}
